insert into verb(infinitive, past, participle, spanish) values('be','was, were','been','Ser/Estar');
insert into verb(infinitive, past, participle, spanish) values('beat','beat','beaten / beat','Batir/Latir/LLevar ritmo');
insert into verb(infinitive, past, participle, spanish) values('become','became','become','Convertirse');
insert into verb(infinitive, past, participle, spanish) values('begin','began','begun','Comenzar');
insert into verb(infinitive, past, participle, spanish) values('bend','bent','bent','Doblar / Curvar');
insert into verb(infinitive, past, participle, spanish) values('bet','bet / betted','bet / betted','Apostar');
insert into verb(infinitive, past, participle, spanish) values('bite','bit','bitten','Morder');
insert into verb(infinitive, past, participle, spanish) values('bleed','bled','bled','Sangrar');
insert into verb(infinitive, past, participle, spanish) values('blow','blew','blown','Soplar');
insert into verb(infinitive, past, participle, spanish) values('break','broke','broken','Romper');
insert into verb(infinitive, past, participle, spanish) values('bring','brought','brought','Traer');
insert into verb(infinitive, past, participle, spanish) values('build','built','built','Construir');
insert into verb(infinitive, past, participle, spanish) values('burn','burned / burnt','burned / burnt','Quemar');
insert into verb(infinitive, past, participle, spanish) values('buy','bought','bought','Comprar');
insert into verb(infinitive, past, participle, spanish) values('catch','caught','caught','Atrapar');
insert into verb(infinitive, past, participle, spanish) values('choose','chose','chosen','Elegir');
insert into verb(infinitive, past, participle, spanish) values('come','came','come','Venir');
insert into verb(infinitive, past, participle, spanish) values('cost','cost','cost','Costar / Valer');
insert into verb(infinitive, past, participle, spanish) values('cut','cut','cut','Cortar');
insert into verb(infinitive, past, participle, spanish) values('do','did','done','Hacer');
insert into verb(infinitive, past, participle, spanish) values('draw','drew','drawn','Dibujar');
insert into verb(infinitive, past, participle, spanish) values('dream','dreamed / dreamt','dreamed / dreamt','Soñar');
insert into verb(infinitive, past, participle, spanish) values('drink','drank','drunk','Beber');
insert into verb(infinitive, past, participle, spanish) values('drive','drove','driven','Conducir');
insert into verb(infinitive, past, participle, spanish) values('eat','ate','eaten','Comer');
insert into verb(infinitive, past, participle, spanish) values('fall','fell','fallen','Caer');
insert into verb(infinitive, past, participle, spanish) values('feel','felt','felt','Sentir');
insert into verb(infinitive, past, participle, spanish) values('fight','fought','fought','Pelear');
insert into verb(infinitive, past, participle, spanish) values('find','found','found','Encontrar');
insert into verb(infinitive, past, participle, spanish) values('fit','fit / fitted','fit / fitted','Quedar bien');
insert into verb(infinitive, past, participle, spanish) values('fly','flew','flown','Volar');
insert into verb(infinitive, past, participle, spanish) values('forget','forgot','forgotten','Olvidar');
insert into verb(infinitive, past, participle, spanish) values('forgive','forgave','forgiven','Perdonar');
insert into verb(infinitive, past, participle, spanish) values('freeze','froze','frozen','Congelar');
insert into verb(infinitive, past, participle, spanish) values('get','got','gotten / got','Obtener');
insert into verb(infinitive, past, participle, spanish) values('give','gave','given','Dar');
insert into verb(infinitive, past, participle, spanish) values('go','went','gone','Ir');
insert into verb(infinitive, past, participle, spanish) values('grow','grew','grown','Crecer');
insert into verb(infinitive, past, participle, spanish) values('hang','hung','hung','Colgar');
insert into verb(infinitive, past, participle, spanish) values('have','had','had','Tener');
insert into verb(infinitive, past, participle, spanish) values('hear','heard','heard','Oir');
insert into verb(infinitive, past, participle, spanish) values('hide','hid','hidden','Ocultar');
insert into verb(infinitive, past, participle, spanish) values('hit','hit','hit','Golpear');
insert into verb(infinitive, past, participle, spanish) values('hold','held','held','Mantener / sujetar');
insert into verb(infinitive, past, participle, spanish) values('hurt','hurt','hurt','Doler / sufrir');
insert into verb(infinitive, past, participle, spanish) values('keep','kept','kept','Conservar');
insert into verb(infinitive, past, participle, spanish) values('know','knew','known','Conocer');
insert into verb(infinitive, past, participle, spanish) values('learn','learned / learnt','learned / learnt','Aprender');
insert into verb(infinitive, past, participle, spanish) values('leave','left','left','Dejar, abandonar');
insert into verb(infinitive, past, participle, spanish) values('lend','lent','lent','Prestar');
insert into verb(infinitive, past, participle, spanish) values('let','let','let','Permitir');
insert into verb(infinitive, past, participle, spanish) values('lie (on a bed)','lay','lain','Recostar');
insert into verb(infinitive, past, participle, spanish) values('lie (not tell truth)','lied','lied','Mentir');
insert into verb(infinitive, past, participle, spanish) values('light','lit / lighted','lit / lighted','Iluminar');
insert into verb(infinitive, past, participle, spanish) values('lose','lost','lost','Perder');
insert into verb(infinitive, past, participle, spanish) values('make','made','made','Hacer');
insert into verb(infinitive, past, participle, spanish) values('mean','meant','meant','Querer decir');
insert into verb(infinitive, past, participle, spanish) values('meet','met','met','Conocer');
insert into verb(infinitive, past, participle, spanish) values('pay','paid','paid','Pagar');
insert into verb(infinitive, past, participle, spanish) values('prove','proved','proven / proved','Proveer');
insert into verb(infinitive, past, participle, spanish) values('put','put','put','Poner');
insert into verb(infinitive, past, participle, spanish) values('quit','quit','quit','Dejar de hacer');
insert into verb(infinitive, past, participle, spanish) values('read','read','read','Leer');
insert into verb(infinitive, past, participle, spanish) values('ride','rode','ridden','Montar');
insert into verb(infinitive, past, participle, spanish) values('rise','rose','risen','Subir / Aumentar');
insert into verb(infinitive, past, participle, spanish) values('run','ran','run','Correr');
insert into verb(infinitive, past, participle, spanish) values('say','said','said','Decir');
insert into verb(infinitive, past, participle, spanish) values('see','saw','seen','Ver');
insert into verb(infinitive, past, participle, spanish) values('seek','sought','sought','Buscar');
insert into verb(infinitive, past, participle, spanish) values('sell','sold','sold','Vender');
insert into verb(infinitive, past, participle, spanish) values('send','sent','sent','Enviar');
insert into verb(infinitive, past, participle, spanish) values('set','set','set','Poner');
insert into verb(infinitive, past, participle, spanish) values('sew','sewed','sewn / sewed','Coser (con hilo)');
insert into verb(infinitive, past, participle, spanish) values('shake','shook','shaken','Sacudir');
insert into verb(infinitive, past, participle, spanish) values('shave','shaved','shaved / shaven','Afeitar');
insert into verb(infinitive, past, participle, spanish) values('shine','shined / shone','shined / shone','Brillar');
insert into verb(infinitive, past, participle, spanish) values('shoot','shot','shot','Disparar');
insert into verb(infinitive, past, participle, spanish) values('show','showed','shown / showed','Mostrar');
insert into verb(infinitive, past, participle, spanish) values('shrink','shrank / shrunk','shrunk','Encoger');
insert into verb(infinitive, past, participle, spanish) values('shut','shut','shut','Cerrar / Encerrar');
insert into verb(infinitive, past, participle, spanish) values('sing','sang','sung','Cantar');
insert into verb(infinitive, past, participle, spanish) values('sink','sank / sunk','sunk','Hundir, Acabar con');
insert into verb(infinitive, past, participle, spanish) values('sit','sat','sat','Sentarse');
insert into verb(infinitive, past, participle, spanish) values('sleep','slept','slept','Dormir');
insert into verb(infinitive, past, participle, spanish) values('slide','slid','slid','Deslizar, Resbalar');
insert into verb(infinitive, past, participle, spanish) values('smell','smelled / smelt','smelled / smelt','Oler');
insert into verb(infinitive, past, participle, spanish) values('sneak','sneaked / snuck','sneaked / snuck','Entrar o Salir a hurtadillas');
insert into verb(infinitive, past, participle, spanish) values('speak','spoke','spoken','Hablar');
insert into verb(infinitive, past, participle, spanish) values('speed','sped / speeded','sped / speeded','Apurarse');
insert into verb(infinitive, past, participle, spanish) values('spell','spelled / spelt','spelled / spelt','Deletrear');
insert into verb(infinitive, past, participle, spanish) values('spend','spent','spent','Gastar');
insert into verb(infinitive, past, participle, spanish) values('spill','spilled / spilt','spilled / spilt','Derramar');
insert into verb(infinitive, past, participle, spanish) values('spit','spit / spat','spit / spat','Escupir');
insert into verb(infinitive, past, participle, spanish) values('split','split','split','Partir / Repartir');
insert into verb(infinitive, past, participle, spanish) values('spread','spread','spread','Tender / Esparcir');
insert into verb(infinitive, past, participle, spanish) values('stand','stood','stood','Estar / Permanecer en un lugar');
insert into verb(infinitive, past, participle, spanish) values('steal','stole','stolen','Robar');
insert into verb(infinitive, past, participle, spanish) values('stick','stuck','stuck','Pegar / Clavar');
insert into verb(infinitive, past, participle, spanish) values('sting','stung','stung','Picar / Escocer');
insert into verb(infinitive, past, participle, spanish) values('stink','stunk / stank','stunk','Apestar');
insert into verb(infinitive, past, participle, spanish) values('strike','struck','struck / stricken','Atacar / Golpear');
insert into verb(infinitive, past, participle, spanish) values('swear','swore','sworn','Jurar');
insert into verb(infinitive, past, participle, spanish) values('sweep','swept','swept','Barrer');
insert into verb(infinitive, past, participle, spanish) values('swim','swam','swum','Nadar');
insert into verb(infinitive, past, participle, spanish) values('swing','swung','swung','Balancear / Oscilar');
insert into verb(infinitive, past, participle, spanish) values('take','took','taken','Tomar');
insert into verb(infinitive, past, participle, spanish) values('teach','taught','taught','Enseñar');
insert into verb(infinitive, past, participle, spanish) values('tear','tore','torn','Rasgar');
insert into verb(infinitive, past, participle, spanish) values('tell','told','told','Decir');
insert into verb(infinitive, past, participle, spanish) values('think','thought','thought','Pensar');
insert into verb(infinitive, past, participle, spanish) values('throw','threw','thrown','Lanzar');
insert into verb(infinitive, past, participle, spanish) values('understand','understood','understood','Entender');
insert into verb(infinitive, past, participle, spanish) values('upset','upset','upset','Sentir mal');
insert into verb(infinitive, past, participle, spanish) values('wake','woke','woken','Despertar');
insert into verb(infinitive, past, participle, spanish) values('wear','wore','worn','Vestir');
insert into verb(infinitive, past, participle, spanish) values('win','won','won','Ganar');
insert into verb(infinitive, past, participle, spanish) values('withdraw','withdrew','withdrawn','Retractarse / Retirarse');
insert into verb(infinitive, past, participle, spanish) values('write','wrote','written','Escribir');