insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('be','was / were','been','Ser/Estar', 'Fue / Estuvo', 'Sido / Estado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('beat','beat','beaten / beat','Batir/Latir/LLevar ritmo', 'Batió', 'Batido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('become','became','become','Convertirse', 'Convirtió', 'Convertido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('begin','began','begun','Comenzar', 'Comenzó', 'Comenzado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('bend','bent','bent','Doblar / Curvar', 'Dobló / Curvó', 'Doblado / Curvado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('bet','bet / betted','bet / betted','Apostar', 'Apostó', 'Apostado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('bite','bit','bitten','Morder', 'Mordió', 'Mordido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('bleed','bled','bled','Sangrar', 'Sangró', 'Sangrado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('blow','blew','blown','Soplar', 'Sopló', 'Soplado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('break','broke','broken','Romper', 'Rompió', 'Roto');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('bring','brought','brought','Traer', 'Trajo', 'Traído');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('build','built','built','Construir', 'Construyó', 'Construido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('burn','burned / burnt','burned / burnt','Quemar', 'Quemó', 'Quemado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('buy','bought','bought','Comprar', 'Compró', 'Comprado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('catch','caught','caught','Atrapar', 'Atrapó', 'Atrapado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('choose','chose','chosen','Elegir', 'Eligió', 'Elegido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('come','came','come','Venir', 'Vino', 'Venido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('cost','cost','cost','Costar / Valer', 'Costó / Valió', 'Costado / Valido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('cut','cut','cut','Cortar', 'Cortó', 'Cortado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('do','did','done','Hacer', 'Hizo', 'Hecho');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('draw','drew','drawn','Dibujar', 'Dibujó', 'Dibujado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('dream','dreamed / dreamt','dreamed / dreamt','Soñar', 'Soñó', 'Soñado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('drink','drank','drunk','Beber', 'Bebió', 'Bebido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('drive','drove','driven','Conducir', 'Condujó', 'Conducido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('eat','ate','eaten','Comer', 'Comió', 'Comido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('fall','fell','fallen','Caer', 'Cayó', 'Caído');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('feel','felt','felt','Sentir', 'Sintió', 'Sentido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('fight','fought','fought','Pelear', 'Peleó', 'Peleado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('find','found','found','Encontrar', 'Encontró', 'Encontrado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('fit','fit / fitted','fit / fitted','Quedar bien', 'Quedó bien', 'Quedado bien');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('fly','flew','flown','Volar', 'Voló', 'Volado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('forget','forgot','forgotten','Olvidar', 'Olvidó', 'Olvidado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('forgive','forgave','forgiven','Perdonar', 'Perdonó', 'Perdonado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('freeze','froze','frozen','Congelar', 'Congeló', 'Congelado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('get','got','gotten / got','Obtener', 'Obtuvo', 'Obtenido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('give','gave','given','Dar', 'Dio', 'Dado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('go','went','gone','Ir', 'Fue', 'Ido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('grow','grew','grown','Crecer', 'Creció', 'Crecido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('hang','hung','hung','Colgar', 'Colgó', 'Colgado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('have','had','had','Tener', 'Tuvo', 'Tenido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('hear','heard','heard','Oir', 'Oyó', 'Oído');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('hide','hid','hidden','Ocultar', 'Ocultó', 'Ocultado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('hit','hit','hit','Golpear', 'Golpeó', 'Golpeado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('hold','held','held','Mantener / sujetar', 'Sujetó', 'Sujetado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('hurt','hurt','hurt','Doler / sufrir', 'Sufrió', 'Sufrido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('keep','kept','kept','Conservar', 'Convirtió', 'Convertido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('know','knew','known','Conocer', 'Conoció', 'Conocido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('learn','learned / learnt','learned / learnt','Aprender', 'Aprendió', 'Aprendido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('leave','left','left','Dejar / abandonar', 'Dejó / Abandonó', 'Dejado / Abandonado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('lend','lent','lent','Prestar', 'Prestó', 'Prestado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('let','let','let','Permitir', 'Permitió', 'Permitido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('lie (on a bed)','lay','lain','Recostar', 'Recostó', 'Recostado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('lie (not tell truth)','lied','lied','Mentir', 'Midió', 'Medido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('light','lit / lighted','lit / lighted','Iluminar', 'Iluminó', 'Iluminado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('lose','lost','lost','Perder', 'Perdió', 'Perdido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('make','made','made','Hacer', 'Hizo', 'Hecho');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('mean','meant','meant','Querer decir', 'Quizó decir', 'Querido decir');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('meet','met','met','Conocer', 'Conoció', 'Conocido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('pay','paid','paid','Pagar', 'Pagó', 'Pagado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('prove','proved','proven / proved','Proveer', 'Proveyó', 'Provisto');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('put','put','put','Poner', 'Puso', 'Puesto');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('quit','quit','quit','Dejar de hacer', 'Dejó de hacer', 'Dejado de hacer');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('read','read','read','Leer', 'Leyó', 'Leído');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('ride','rode','ridden','Montar', 'Montó', 'Montado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('rise','rose','risen','Subir / Aumentar', 'Subió / Aumentó', 'Subido / Aumentado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('run','ran','run','Correr', 'Corrió', 'Corrido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('say','said','said','Decir', 'Dijo', 'Dicho');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('see','saw','seen','Ver', 'Vio', 'Visto');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('seek','sought','sought','Buscar', 'Buscó', 'Buscado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('sell','sold','sold','Vender', 'Vendío', 'Vendido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('send','sent','sent','Enviar', 'Envió', 'Enviado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('set','set','set','Poner', 'Puso', 'Puesto');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('sew','sewed','sewn / sewed','Coser (con hilo)', 'Cosió', 'Cosido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('shake','shook','shaken','Sacudir', 'Sacudió', 'Sacudido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('shave','shaved','shaved / shaven','Afeitar', 'Afeitó', 'Afeitado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('shine','shined / shone','shined / shone','Brillar', 'Brilló', 'Brillado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('shoot','shot','shot','Disparar', 'Disparó', 'Disparado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('show','showed','shown / showed','Mostrar', 'Mostró', 'Mostrado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('shrink','shrank / shrunk','shrunk','Encoger', 'Encogió', 'Encogido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('shut','shut','shut','Cerrar / Encerrar', 'Cerró / Encerró', 'Cerrado / Encerrado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('sing','sang','sung','Cantar', 'Cantó', 'Cantado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('sink','sank / sunk','sunk','Hundir / Acabar con', 'Hundió', 'Hundido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('sit','sat','sat','Sentarse', 'Sentó', 'Sentado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('sleep','slept','slept','Dormir', 'Durmió', 'Dormido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('slide','slid','slid','Deslizar / Resbalar', 'Deslizó / Resbaló', 'Deslizado / Resbalado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('smell','smelled / smelt','smelled / smelt','Oler', 'Olió', 'Olido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('sneak','sneaked / snuck','sneaked / snuck','Entrar o Salir a hurtadillas', 'Entró o Salió a hurtadillas', 'Entrado o Salido a hurtadillas');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('speak','spoke','spoken','Hablar', 'Habló', 'Hablado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('speed','sped / speeded','sped / speeded','Apurarse', 'Apuró', 'Apurado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('spell','spelled / spelt','spelled / spelt','Deletrear', 'Deletreó', 'Deletreado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('spend','spent','spent','Gastar', 'Gastó', 'Gastado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('spill','spilled / spilt','spilled / spilt','Derramar', 'Derramó', 'Derramado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('spit','spit / spat','spit / spat','Escupir', 'Escupió', 'Escupido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('split','split','split','Partir / Repartir', 'Partió / Repartió', 'Partido / Repartido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('spread','spread','spread','Tender / Esparcir', 'Tendió / Esparció', 'Tendido / Esparcido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('stand','stood','stood','Estar / Permanecer en un lugar', 'Estuvo / Permanecio en un lugar', 'Estado / Pertenecido en un lugar');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('steal','stole','stolen','Robar', 'Robó', 'Robado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('stick','stuck','stuck','Pegar / Clavar', 'Clavó', 'Clavado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('sting','stung','stung','Picar / Escocer', 'Picó / Escoció', 'Picado / Escocido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('stink','stunk / stank','stunk','Apestar', 'Apestó', 'Apestado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('strike','struck','struck / stricken','Atacar / Golpear', 'Atacó / Golpeó', 'Atacado / Golpeado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('swear','swore','sworn','Jurar', 'Juró', 'Jurado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('sweep','swept','swept','Barrer', 'Barrió', 'Barrido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('swim','swam','swum','Nadar', 'Nadó', 'Nadado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('swing','swung','swung','Balancear / Oscilar', 'Balanceó / Oscilo', 'Balaceado / Oscilado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('take','took','taken','Tomar', 'Tomó', 'Tomado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('teach','taught','taught','Enseñar', 'Enseño', 'Enseñado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('tear','tore','torn','Rasgar', 'Rasgó', 'Rasgado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('tell','told','told','Decir', 'Dijo', 'Dejado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('think','thought','thought','Pensar', 'Pensó', 'Pensado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('throw','threw','thrown','Lanzar', 'Lanzó', 'Lanzado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('understand','understood','understood','Entender', 'Entendió', 'Entendido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('upset','upset','upset','Sentir mal', 'Sintió Mal', 'Sendito Mal');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('wake','woke','woken','Despertar', 'Despertó', 'Despertado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('wear','wore','worn','Vestir', 'Vistió', 'Vestido');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('win','won','won','Ganar', 'Ganó', 'Ganado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('withdraw','withdrew','withdrawn','Retractarse / Retirarse', 'Retractó / Retiró', 'Retractactado / Retirado');
insert into verb(infinitive, past, participle, spanish, spanish_past, spanish_participle) values('write','wrote','written','Escribir', 'Escribió', 'Escrito');
